language: python
python:
- '3.8'
install: pip install -r requirements.txt
script: "./scripts/verify.sh"
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: oIcacHviU8EvuPtjsasfsvMcNNB+1bTHU6vCjmvwyMgVHXrVrem3Qp2enjyAQGgvhkeaGFVFxZfhVmK1jlRyCxG1NDUH4Gd8CBSVqmA+oj/g8ItTUtkSbGbXjzNrWK9RHA+ik5G61ZXEFPjj7eVbblrkQL/evDfV9fhazyRKsTRMRIEowo1YOIH6Oe4DDK88HSAAhkxSSLhWUz/PekpGDEn68CVcLtVIs9O3RX1sIF2vRBvqiCtxATCErOBz6W7BTZyZYU/1vz2S1Ci0N2+Ph+C631oD3Lf6dzVlzpFxLgx2rAdG4zaoalmeB5xIKvTmbhKI008sxXraEYtEXsmWOprkKlqSXzKmqx1KlNMZ0O3G6hGYbys4Bs6fxzgICc066pVjDVHjGIv1F6ehE0nHnVcDn1jhzOuikevxAigv5WQZRkkySYfv6EdJuI3AWb9gngsgyNy4u8Fn+CQrbCOs3CHg3kSOOmW77OXN0xFJgLU88j0TiX8vb8q78yJVoujteE0reuT1vzhu/OVTuX8RpOtouU/fcDvkN0LO2GHzbVpj56dH3/FVD9lwCso0bCjYML9X1qPHcYYwtqpyIQWrRB2j0Ou80FmjntQ3Esi+j9qCBY3jsa5Izw8/KqcP0tkvQNU1tZKdLIXGHgScWTSeSlWn8RC+JEtQOyvgLhf8AvM=
