language: python
python:
- '3.8'
install: pip install -r requirements.txt
script: ./scripts/verify.sh
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: fOkuefG2x95+yWoLafo+DUL8zPLFL7qRTuSLrHMAkAiFlF9mgFD5k6wlDuhdm4hcBN7HN+5/vlRR2XC08TQXieor9DgUVnLsYbaRwX/1WUC76R6X/mZZkIf6OQe9ZoD/9Qr3jX+WQmGi8aB+ASNSg9SWCEupKXQxzhU3/5P5RdI4H18U78//UFDjqsSZFmeiYC3f5xvO0OVmT9XspKDStW3qCgdBXdOBiE1T8Fvt4NqnEiNOpuG+Rs4Gjop13z+CEpFKstBFduSuOxL63y8ZcK3tqlX1Um5ngrplaIJWNaWfZAkJKsnedU7WQh/EjmTE0ikek38mihOkvEWS0AhhzbSYyIbAsjUP47xToysnxdAsgHEtjfLmE67GCkbhIcpUBxmYrEEfUNZl817J2O1IwDLvCp0084eg+2FWpuiL0OhqpAqIPmG3CRmVx+8rz9ToW2/q7xwRBs0AzBZsatJElSO0tYFBKYGF5hhet66BnbjNEo5c5jiXaZeygJChzrXlQutuxZIvyiyRcjIrzh98gLp2FAcOg7I96e7o4g32FQFRliVKnEb+hJgZadUQRXnKZ6M/gB2V8xfxE8h5hUXFFZU3eNgW9QuF3e7abTGmZkRvw2MqDVzv8rgS2hD1NswJNB+y/p0EUnUzf+7myRE20wQRac2oRCa89XLOEbvZd28=
