from typing import ContextManager

def meta(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def link(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def div(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def script(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def table(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def thead(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def tbody(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def tr(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
def td(content: str | None = None, **kwargs: str) -> ContextManager[None]: ...
